export const actionTypes = {
    NEW_INCOME: 'NEW_INCOME',
    EDIT_INCOME: 'EDIT_INCOME' ,
    REMOVE_INCOME: 'REMOVE_INCOME',
    NEW_EXPENSE: 'NEW_EXPENSE',
    EDIT_EXPENSE: 'EDIT_EXPENSE',
    REMOVE_EXPENSE: 'REMOVE_EXPENSE',
    NEW_CATEGORY: 'NEW_CATEGORY',
    EDIT_CATEGORY: 'EDIT_CATEGORY',
    REMOVE_CATEGORY: 'REMOVE_CATEGORY'
}